import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createInitialUserInDbOnSignIn } from "@/server/actions/user.action";
import { currentUser } from "@clerk/nextjs/server";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Checking if there is User Signed In
  // Calling Server Action Function To Create User On Sign-In if there is no User based on ClerkId
  const user = await currentUser();
  if (user) await createInitialUserInDbOnSignIn()

  return (
    <ClerkProvider>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <Toaster/>
          {children}
        </body>
      </html>
      
    </ClerkProvider>
  );
}
